[project]
name = "cf-submit"
version = "0.1.0"
description = "something something selenium go brrr"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "flask>=3.1.2",
    "selenium>=4.39.0",
]
